# Site settings
title: 帅比_程的个人空间
description: 帅比_程的个人空间
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://blog.aaaxiao.xyz/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 帅比_程
user_description: 装逼，耍帅
user_title: 房子建筑师
email:  
twitter_username:  
github_username:   
gplus_username:   

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
